### ISSUE TITLE
Running the plugin on a Raspi

### ISSUE THREAD

**Issue by r32er** [JSRossiter/homebridge-spotify#1]
Hello, 

I was glad to find your plugin to control spotify with Homekit. unfortunately it has to run on a mac. 

ist it possible to run it on a raspi too? Cause my Homebridge run on it, not on a Mac.

thank you in advance

**Comment by JSRossiter** [comment]
no sorry, it just uses applescript to interact with the spotify app.  You would need to interact with the spotify api to control it from a raspi
